#ifndef _PICNIC_CONST_H_
#define _PICNIC_CONST_H_

#define PICNIC_MAX_SERVO_CHANNELS 6
#define PICNIC_MAX_PWM_CHANNELS 6
#define PICNIC_BUFFER_LEN 512

#define PICNIC_DEVICE_NAME "picnc"
#define PICNIC_CLASS_NAME "picnc"

#define K_BUFFER_LEN 1024

/* PiCNC protocol commands */
#define PICNIC_PROTO_CMD_READ_DEVICE_ID		0x00
#define PICNIC_PROTO_CMD_READ_INPUTS		0x01
#define PICNIC_PROTO_CMD_READ_ENCODERS		0x02
#define PICNIC_PROTO_CMD_READ_OUTPUTS		0x03
#define PICNIC_PROTO_CMD_READ_SERVOS		0x04
#define PICNIC_PROTO_CMD_READ_PWMS		0x05
#define PICNIC_PROTO_CMD_READ_SETTINGS		0x06
#define PICNIC_PROTO_CMD_WRITE_OUTPUTS		0x07
#define PICNIC_PROTO_CMD_WRITE_SERVOS		0x08
#define PICNIC_PROTO_CMD_WRITE_PWMS		0x09
#define PICNIC_PROTO_CMD_WRITE_DIR_HOLD		0xF0
#define PICNIC_PROTO_CMD_WRITE_STEP_HOLD	0xF1
#define PICNIC_PROTO_CMD_IS_EMPTY		0xFF

/* PiCNC device registers (will be removed) */
#define GPIO_REG_ADDR_DEVICE_ID		0x0000
#define GPIO_REG_PULSEGEN_STEP_HOLD	0x0004
#define GPIO_REG_PULSEGEN_1		0x0008
#define GPIO_REG_PULSEGEN_2		0x0010
#define GPIO_REG_PULSEGEN_3		0x0018
#define GPIO_REG_PULSEGEN_4		0x0020
#define GPIO_REG_PULSEGEN_DIR_HOLD	0x0028
#define GPIO_REG_INPUTS			0x002C
#define GPIO_REG_OUTPUTS		0x0030
#define GPIO_REG_INTERRUPT		0x003C

#endif
